name: ibis-dev
channels:
  - conda-forge
dependencies:
  # This file should have all the dependencies for development excluding the specific to the backends.

  # Ibis hard dependencies
  - multipledispatch>=0.6.0
  - numpy>=1.19
  - pandas>=0.25 # XXX pymapd does not support pandas 1.0, only 0.25 series
  - pytz>=2020.1
  - regex>=2020.7
  - toolz>=0.10

  # Ibis soft dependencies
  # TODO This section is probably not very accurate right now (some dependencies may be should be in the backends files)
  - sqlalchemy>=1.3
  - graphviz
  - openjdk=8
  - pytables>=3.6.0
  - python-graphviz
  - python-hdfs>=2.0.16

  # Dev tools
  - black=19.10b0
  - click>=7.1 # few scripts in ci/
  - conda-build # feedstock
  - cmake>=3.18
  - flake8>=3.8
  - isort>=5.3
  - jinja2>=2.11 # feedstock
  - mypy>=0.782
  - plumbum>=1.6 # few scripts in ci/ and dev/
  - pre-commit>=2.6
  - pydocstyle=4.0.1
  - pygit2 # dev/genrelease.py
  - pytest=5.4.2 # TODO: there are problems in future versions, review eventually
  - pytest-cov>=2.10
  - pytest-mock>=3.1
  - pytest-xdist
  - ruamel.yaml>=0.16 # feedstock
  - libiconv>=1.15  # bug in repo2docker, see https://github.com/jupyter/repo2docker/issues/758
  - xorg-libxpm
  - xorg-libxrender

  # Docs
  - ipython>=7.17
  - jupyter>=1.0
  - matplotlib>=3.3
  - nbconvert
  - nbsphinx>=0.7
  - nomkl
  - pyarrow>=0.12 # must pin again otherwise strange things happen
  - sphinx=2.0.1
  - sphinx-releases
  - sphinx_rtd_theme>=0.5
  - semantic_version<2.7 # https://github.com/ibis-project/ibis/issues/2027
  - pip
  - pip:
    - git+https://github.com/datapythonista/pysuerga
