name: Main

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  PYTHON_VERSION: "3.8"
  CONTAINERS_TO_START: "impala postgres"

jobs:
  test_windows:
    name: Test windows
    runs-on: windows-latest
    services:
      mysql:
        image: mariadb:10.3.23
        env:
          MYSQL_USER: ibis
          MYSQL_PASSWORD: ibis
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: add conda to path
      run: echo "::add-path::/usr/share/miniconda/bin"

    - name: set up conda
      run: |
        conda update -n base -c anaconda conda
        conda install -n base -c anaconda python=${PYTHON_VERSION}
        conda env update -n base --file=ci/requirements-dev.yml
        conda env update -n base --file=ci/requirements-docs.yml
        python -m pip install -e .

    - name: set up test data
      run: |
        python ci/datamgr.py download
        python ci/datamgr.py mysql

    - name: run tests
      run: pytest --tb=short \
                  --junitxml="junit-$(PYTHON_VERSION).xml" \
                  -n auto \
                  -ra ibis \
                  -m "not backend and not clickhouse and not impala and not hdfs and not bigquery and not omniscidb and not postgis and not postgresql"

  docs_lint_package_benchmark:
    name: Docs, lint, package and benckmark
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: add conda to path
      run: echo "::add-path::/usr/share/miniconda/bin"

    - name: set up conda
      run: |
        conda update -n base -c anaconda conda
        conda install -n base -c anaconda python=${PYTHON_VERSION}
        conda env update -n base --file=ci/requirements-dev.yml
        conda env update -n base --file=ci/requirements-docs.yml
        python -m pip install -e .

    - name: black
      run: black --check .
      if: always()

    - name: mypy
      # TODO: mypy has errors that need to be fixed before it can be added
      run: mypy --ignore-missing-imports ibis || true
      if: always()

    - name: pydocstyle
      # TODO: change match-dir when docstrings are fixed for other backends
      run: pydocstyle --match-dir="(ibis|omniscidb)"
      if: always()

    - name: isort
      # TODO: isort has errors that need to be fixed before it can be added
      run: isort --quiet --recursive || true
      if: always()

    - name: feedstock
      run: ./ci/feedstock.py test --python 3.7
      if: always()

    - name: publish feedstock artifact
      uses: actions/upload-artifact@master
      with:
        name: LinuxCondaPackage
        path: /tmp/ibis/packages
      if: github.event_name == 'push'

    - name: benckmark
      # TODO: restore benchmarks before merging, disabling to speed up builds
      run: echo "TODO: restore benchmarks before merging" # ./ci/benchmark.sh azure "${{ github.sha }}"
      if: always()

    - name: start backend containers
      run: ./ci/start_backend_containers.sh $CONTAINERS_TO_START
      if: always()

    - name: build web and docs
      run: |
        mkdir ibis-project.org
        echo "ibis-project.org" > ibis-project.org/CNAME
        touch ibis-project.org/.nojekyll
        python -m pysuerga /ibis/docs/web --target-path=ibis-project.org/
        sphinx-build -b html docs/source ibis-project.org/docs -W -T --keep-going
      if: always()

    - name: set up ssh
      run: |
        mkdir ~/.ssh
        base64 --decode --ignore-garbage <<< "${{ secrets.ibis_gh_token }}" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      if: github.event_name == 'push'

    - name: push web to GitHub pages
      run: |
        cd ibis-project.org

        git init
        git checkout -b gh-pages
        git remote add origin git@github.com:ibis-project/docs.ibis-project.org
        git config user.name 'Ibis Documentation Bot'
        git config user.email ''

        git add --all .
        git commit -m "Docs from ibis at $(Build.SourceVersion)"
        git push --force origin gh-pages
      if: github.event_name == 'push'
