name: Main

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  PYTHON_VERSION: "3.8"

jobs:
  setup_miniconda:
    name: Setup miniconda task
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup conda
      uses: goanpeca/setup-miniconda@v2
      with:
        python-version: ${PYTHON_VERSION}
        auto-activate-base: false
        environment-file: ci/requirements-dev.yml
        activate-environment: ibis-dev

    - name: which python and pandas version
      run: |
        which python
        python -c "import pandas; print(pandas.__version__)"

  actions_conda:
    name: Setup GitHub actions conda
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup conda
      run: |
        echo "::add-path::/usr/share/miniconda/bin"
        conda update -n base -c anaconda conda
        conda install -n base -c anaconda python=${PYTHON_VERSION}
        conda env update -n base --file=ci/requirements-dev.yml

    - name: which python and pandas version
      run: |
        which python
        python -c "import pandas; print(pandas.__version__)"
