name: Main

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  ENV_FILE: environment.yml

jobs:
  setup_miniconda:
    name: Test setup miniconda task
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: ibis-dev
        environment-file: ci/requirements-dev.yml
        python-version: 3.8

    - name: python -c "import pandas; print(pandas.__version__)"
      run: python -c "import pandas; print(pandas.__version__)"

  test_conda:
    name: Test Conda
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: python --version
      run: python --version

    - name: conda update -n base -c anaconda conda
      run: conda update -n base -c anaconda conda

    - name: find .
      run: find .

    - name: cat ci/requirements-dev.yml
      run: cat ci/requirements-dev.yml

    - name: conda env update -n base --file=ci/requirements-dev.yml
      run: conda env update -n base --file=ci/requirements-dev.yml
      if: always()

    - name: python --version
      run: python --version

    - name: python -c "import pandas; print(pandas.__version__)"
      run: |
        conda activate base
        python -c "import pandas; print(pandas.__version__)"
