name: Main

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ubuntu-latest
        python_version: ["3.7", "3.8"]
    env:
      # Removing everything that needs a running (docker) backend for now
      PYTEST_EXPRESSION: "not udf and not mysql and not clickhouse and not impala and not kudu and not hdfs and not omniscidb and not spark and not pyspark"
    services:
      postgres:
        image: shajekpivotal/ibis-docker-postgres-9.5
        ports:
          - 5432
        env:
          POSTGRES_PASSWORD: ''

    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: set up environment ${{ matrix.pytest_version }}
      run: ./ci/setup_env.sh
      shell: bash

    - name: set up backend
      run: |
        conda env update -n base --file=ci/deps/postgres.yml
        python ci/datamgr.py download
        python ci/datamgr.py postgres

    - name: run tests
      run: ./ci/run_tests.sh "$PYTEST_EXPRESSION"
      shell: bash


  Lint_package_benchmark:
    name: Lint, package and benckmark
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: set up environment
      run: ./ci/setup_env.sh

    - name: black
      run: black --check .
      if: always()

    - name: mypy
      # TODO: mypy has errors that need to be fixed before it can be added
      run: mypy --ignore-missing-imports ibis || true
      if: always()

    - name: pydocstyle
      # TODO: change match-dir when docstrings are fixed for other backends
      run: pydocstyle --match-dir="(ibis|omniscidb)"
      if: always()

    - name: isort
      # TODO: isort has errors that need to be fixed before it can be added
      run: isort --check-only . || true
      if: always()

    - name: feedstock
      run: |
        ./ci/feedstock.py clone
        ./ci/feedstock.py update
        ./ci/feedstock.py build --python 3.7
        ./ci/feedstock.py deploy /usr/share/miniconda/conda-bld/
      if: always()

    - name: publish feedstock artifact
      uses: actions/upload-artifact@master
      with:
        name: LinuxCondaPackage
        path: /tmp/ibis/packages
      if: github.event_name == 'push'

    - name: benckmark
      run: ./ci/benchmark.sh azure "${{ github.sha }}"
      if: always()
