name: Main

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  ENV_FILE: environment.yml

jobs:
  setup_miniconda:
    name: Test setup miniconda task
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup conda
      uses: goanpeca/setup-miniconda@v1
      with:
        python-version: 3.8
        auto-activate-base: false
        environment-file: ci/requirements-dev.yml
        activate-environment: ibis-dev

    - name: which python
      run: which python

    - name: python -c "import pandas; print(pandas.__version__)"
      run: python -c "import pandas; print(pandas.__version__)"

  test_conda:
    name: Test Conda
    runs-on: ubuntu-latest
    steps:

    - name: which conda
      run: which conda

    - name: conda env list
      run: conda env list

    - name: find /usr/share/miniconda
      run: find /usr/share/miniconda

    - name: Add conda to path
      run: echo "::add-path::/usr/share/miniconda/bin"

    - name: Checkout
      uses: actions/checkout@v1

    - name: python --version
      run: python --version

    - name: conda update -n base -c anaconda conda
      run: conda update -n base -c anaconda conda

    - name: conda install python=3.8
      run: conda install python=3.8

    - name: conda env update -n base --file=ci/requirements-dev.yml
      run: conda env update -n base --file=ci/requirements-dev.yml
      if: always()

    - name: which python
      run: which python

    - name: which python
      run: |
        source activate base
        which python

    - name: python -c "import pandas; print(pandas.__version__)"
      run: |
        source activate base
        python -c "import pandas; print(pandas.__version__)"
